# Generated by Django 2.1.3 on 2018-11-04 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Signos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('data', models.CharField(default=' ', max_length=200)),
                ('descricao', models.TextField()),
                ('img', models.CharField(max_length=1000)),
                ('nomelink', models.CharField(max_length=200)),
            ],
        ),
    ]
